name = "lkm-cdn3-dev"
main = "src/index.ts"
compatibility_date = "2023-05-10"
compatibility_flags = ["nodejs_compat"]
workers_dev = false

# Specifies the r2 buckets. r2 bucket names are scoped to your account (not global). The buckets should be publicly inaccessible.
r2_buckets = [
    { binding = "ATTACHMENT_BUCKET", bucket_name = "lkm-stage-attachments", preview_bucket_name = "lkm-stage-attachments" },
    { binding = "BACKUP_BUCKET", bucket_name = "lkm-stage-backups", preview_bucket_name = "lkm-stage-backups" }
]

durable_objects.bindings = [
    { name = "ATTACHMENT_UPLOAD_HANDLER", class_name = "AttachmentUploadHandler" },
    { name = "BACKUP_UPLOAD_HANDLER", class_name = "BackupUploadHandler" }
]

[[migrations]]
tag = "v1"
new_sqlite_classes = ["AttachmentUploadHandler", "BackupUploadHandler"]

[env.production]
name = "lkm-cdn3"
logpush = true
durable_objects.bindings = [
    { name = "ATTACHMENT_UPLOAD_HANDLER", class_name = "AttachmentUploadHandler" },
    { name = "BACKUP_UPLOAD_HANDLER", class_name = "BackupUploadHandler" }
]
r2_buckets = [
    { binding = "ATTACHMENT_BUCKET", bucket_name = "lkm-attachments", preview_bucket_name = "lkm-attachments" },
    { binding = "BACKUP_BUCKET", bucket_name = "lkm-backups", preview_bucket_name = "lkm-backups" }
]

[env.staging]
name = "lkm-stage-cdn3"
durable_objects.bindings = [
    { name = "ATTACHMENT_UPLOAD_HANDLER", class_name = "AttachmentUploadHandler" },
    { name = "BACKUP_UPLOAD_HANDLER", class_name = "BackupUploadHandler" }
]
r2_buckets = [
    { binding = "ATTACHMENT_BUCKET", bucket_name = "lkm-stage-attachments", preview_bucket_name = "lkm-stage-attachments" },
    { binding = "BACKUP_BUCKET", bucket_name = "lkm-stage-backups", preview_bucket_name = "lkm-stage-backups" }
]

# To set an auth secret,
# wrangler secrets put SHARED_AUTH_SECRET 
